version: '3'
services:
  nginx:
    image: nginx
    volumes:
      - ./site.template:/etc/nginx/conf.d/site.template
      - ./frontEnd/dist:/home/site/vue-think-web
      - ./php:/home/site/vue-think-server
    depends_on:
      - php-fpm
    ports:
      - "80:80"
    command: /bin/bash -c "cat /etc/nginx/conf.d/site.template > /etc/nginx/conf.d/default.conf && exec nginx -g 'daemon off;'"
    networks: 
      - php
  php-fpm:
    container_name: php-fpm
    image: crunchgeek/php-fpm:7.2
    environment: 
     - PHP_ACCESS_LOG=on
     - PHP_UID=1000
     - PHP_GID=1000
     - PHP_HOME=/app
     - PHP_USER=php-fpm
     - PHP_POOL_PATH=/app/www.conf
    volumes:
      - ./php:/home/site/vue-think-server
      - ./www.conf:/app/www.conf
    networks: 
      - php
networks: 
  php:
    driver: bridge