version: 2

defaults: &defaults
  working_directory: ~/project/vue-think
  docker:
    - image: circleci/node:8.12

jobs:
  install:
    <<: *defaults
    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-vue-think-{{ .Branch }}-{{ checksum "frontEnd/package.json" }}
          - v1-vue-think-{{ .Branch }}-

      - run: cd frontEnd && npm install

      - save_cache:
          key: v1-vue-think-{{ .Branch }}-{{ checksum "frontEnd/package.json" }}
          paths:
            - node_modules
      - persist_to_workspace:
          root: ~/project
          paths:
            - vue-think
  build:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/project
      - run: cd frontEnd && npm run build
  deploy:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/project
      - run: 
          name: Deploy
          command: scp -o  StrictHostKeyChecking=no -i ~/project/vue-think/frontEnd/dist $SSH_USER@$SSH_HOST:$DEPLOY_PATH
workflows:
  version: 2
  install-and-parallel-test:
    jobs:
      - install
      - build:
          requires:
            - install
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master


